services:
    _defaults:
        autowire: false
        autoconfigure: false

    f1monkey.eve_esi.guzzle:
        class: GuzzleHttp\Client

    f1monkey.eve_esi.serializer.scope_handler:
        class: F1Monkey\EveEsiBundle\Serializer\Handler\ScopeHandler
        tags:
            - { name: 'jms_serializer.subscribing_handler'}

    f1monkey.eve_esi.oauth.request_prototype:
        class: F1Monkey\EveEsiBundle\ValueObject\OAuthRequest
        arguments:
            $arrayTransformer: '@jms_serializer'
            $baseUrl: '%f1monkey.eve_esi.oauth.base_url%'
            $clientId: '%f1monkey.eve_esi.oauth.client_id%'
            $clientSecret: '%f1monkey.eve_esi.oauth.client_secret%'

    f1monkey.eve_esi.oauth.request_exception_factory:
        class: F1Monkey\EveEsiBundle\Factory\OAuth\RequestExceptionFactory
        arguments:
            $serializer: '@jms_serializer'

    f1monkey.eve_esi.oauth.api_client:
        class: F1Monkey\EveEsiBundle\Service\ApiClient\ApiClient
        arguments:
            $httpClient: '@f1monkey.eve_esi.guzzle'
            $serializer: '@jms_serializer'
            $exceptionFactory: '@f1monkey.eve_esi.oauth.request_exception_factory'

    f1monkey.eve_esi.oauth.api_client.validation_proxy:
        class: F1Monkey\EveEsiBundle\Service\ApiClient\RequestValidationProxy
        arguments:
            $validator: '@validator'
            $apiClient: '@f1monkey.eve_esi.oauth.api_client'

    F1Monkey\EveEsiBundle\Factory\OAuth\OAuthRequestFactoryInterface:
        class: F1Monkey\EveEsiBundle\Factory\OAuth\OAuthRequestFactory
        arguments:
            $requestPrototype: '@f1monkey.eve_esi.oauth.request_prototype'

    F1Monkey\EveEsiBundle\Factory\OAuth\RedirectUrlFactoryInterface:
        class: F1Monkey\EveEsiBundle\Factory\OAuth\RedirectUrlFactory
        arguments:
            $oauthUrl: '%f1monkey.eve_esi.oauth.base_url%'
            $redirectUrl: '%f1monkey.eve_esi.oauth.callback_url%'
            $clientId: '%f1monkey.eve_esi.oauth.client_id%'

    F1Monkey\EveEsiBundle\Service\OAuth\OAuthServiceInterface:
        class: F1Monkey\EveEsiBundle\Service\OAuth\OAuthService
        arguments:
            $redirectUrlFactory: '@F1Monkey\EveEsiBundle\Factory\OAuth\RedirectUrlFactoryInterface'
            $oauthRequestFactory: '@F1Monkey\EveEsiBundle\Factory\OAuth\OAuthRequestFactoryInterface'
            $apiClient: '@f1monkey.eve_esi.oauth.api_client.validation_proxy'