services:
    _defaults:
        autowire: false
        autoconfigure: false

    _instanceof:
        F1monkey\EveEsiBundle\Factory\Esi\AbstractEsiRequestFactory:
            calls:
                - ['setRequestPrototype', ['@f1monkey.eve_esi.esi.request_prototype']]

    f1monkey.eve_esi.guzzle:
        class: GuzzleHttp\Client

    f1monkey.eve_esi.esi.request_prototype:
        class: F1monkey\EveEsiBundle\ValueObject\EsiRequest
        arguments:
            $arrayTransformer: '@jms_serializer'
            $baseUrl: '%f1monkey.eve_esi.esi.base_url%'

    f1monkey.eve_esi.esi.request_exception_factory:
        class: F1monkey\EveEsiBundle\Factory\Esi\RequestExceptionFactory
        arguments:
            $serializer: '@jms_serializer'

    F1monkey\EveEsiBundle\EventListener\RequestListener:
        class: F1monkey\EveEsiBundle\EventListener\RequestListener
        tags:
            - { name: 'kernel.event_listener', event: F1monkey\EveEsiBundle\Event\RequestAfterEvent, method: 'injectEsiResponseMetadata' }
            - { name: 'kernel.event_listener', event: F1monkey\EveEsiBundle\Event\RequestAfterEvent, method: 'injectEsiResponseMetadata' }

    f1monkey.eve_esi.esi.api_client:
        class: F1monkey\EveEsiBundle\Service\ApiClient\ApiClient
        arguments:
            $httpClient: '@f1monkey.eve_esi.guzzle'
            $serializer: '@jms_serializer'
            $eventDispatcher: '@event_dispatcher'
            $exceptionFactory: '@f1monkey.eve_esi.esi.request_exception_factory'

    f1monkey.eve_esi.esi.api_client.validation_proxy:
        class: F1monkey\EveEsiBundle\Service\ApiClient\RequestValidationProxy
        arguments:
            $validator: '@validator'
            $apiClient: '@f1monkey.eve_esi.esi.api_client'

    F1monkey\EveEsiBundle\Factory\Esi\VerifyAccessTokenRequestFactoryInterface:
        class: F1monkey\EveEsiBundle\Factory\Esi\VerifyAccessTokenRequestFactory

    F1monkey\EveEsiBundle\Service\Esi\VerifyTokenServiceInterface:
        class: F1monkey\EveEsiBundle\Service\Esi\VerifyTokenService
        arguments:
            $apiClient: '@f1monkey.eve_esi.esi.api_client.validation_proxy'
            $requestFactory: '@F1monkey\EveEsiBundle\Factory\Esi\VerifyAccessTokenRequestFactoryInterface'

    F1monkey\EveEsiBundle\Factory\Esi\MarketRequestFactoryInterface:
        class: F1monkey\EveEsiBundle\Factory\Esi\MarketRequestFactory

    F1monkey\EveEsiBundle\Service\Esi\MarketServiceInterface:
        class: F1monkey\EveEsiBundle\Service\Esi\MarketService
        arguments:
            $apiClient: '@f1monkey.eve_esi.esi.api_client.validation_proxy'
            $requestFactory: '@F1monkey\EveEsiBundle\Factory\Esi\MarketRequestFactoryInterface'